/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type SpotReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "spot";
};

export type SpotCard = {
  _type: "spotCard";
  spot?: SpotReference;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
};

export type ArticleBody = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3";
      listItem?: "bullet";
      markDefs?: Array<
        {
          _key: string;
        } & Link
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & CaptionedImage)
  | ({
      _key: string;
    } & SpotCard)
  | ({
      _key: string;
    } & PullQuote)
>;

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3";
  listItem?: "bullet";
  markDefs?: Array<
    {
      _key: string;
    } & Link
  >;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type PullQuote = {
  _type: "pullQuote";
  text?: string;
  source?: string;
};

export type Link = {
  _type: "link";
  href?: string;
};

export type ArticleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "article";
};

export type HeroSlide = {
  _type: "heroSlide";
  tag?: string;
  kicker?: string;
  title?: string;
  ctaLabel?: string;
  image?: AltImage;
  reference?: ArticleReference | SpotReference;
  url?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CaptionedImage = {
  _type: "captionedImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type AltImage = {
  _type: "altImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  tagline?: string;
  description?: string;
  heroSlides?: Array<
    {
      _key: string;
    } & HeroSlide
  >;
  pickupSpots?: Array<
    {
      _key: string;
    } & SpotReference
  >;
  pickupArticles?: Array<
    {
      _key: string;
    } & ArticleReference
  >;
  operatorName?: string;
  socialLinks?: Array<string>;
  ogImage?: AltImage;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  body?: RichText;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?: "guide" | "interview" | "history" | "course" | "report";
  excerpt?: string;
  mainImage?: AltImage;
  publishedAt?: string;
  updatedAt?: string;
  body?: ArticleBody;
  relatedSpots?: Array<
    {
      _key: string;
    } & SpotReference
  >;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Spot = {
  _id: string;
  _type: "spot";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  category?: "terrace" | "kura" | "spot" | "local";
  genres?: Array<string>;
  status?: "open" | "paused" | "closed";
  summary?: string;
  location?: Geopoint;
  lastVerifiedAt?: string;
  address?: string;
  hours?: string;
  holidays?: string;
  website?: string;
  instagram?: string;
  phone?: string;
  body?: RichText;
  mainImage?: AltImage;
  gallery?: Array<
    {
      _key: string;
    } & AltImage
  >;
  seo?: Seo;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | SpotReference
  | SpotCard
  | Seo
  | ArticleBody
  | RichText
  | PullQuote
  | Link
  | ArticleReference
  | HeroSlide
  | SanityImageAssetReference
  | CaptionedImage
  | AltImage
  | SiteSettings
  | Page
  | Slug
  | Article
  | SanityImageCrop
  | SanityImageHotspot
  | Spot
  | Geopoint
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;

// Source: sanity/lib/queries.ts
// Variable: spotSlugsQuery
// Query: *[_type == "spot" && defined(slug.current)]{ "slug": slug.current }
export type SpotSlugsQueryResult = Array<{
  slug: string | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: spotBySlugQuery
// Query: *[_type == "spot" && slug.current == $slug][0]{    _id,    name,    "slug": slug.current,    category,    genres,    status,    summary,    address,    hours,    holidays,    website,    instagram,    lastVerifiedAt,    location,    body,    mainImage{      alt,      asset->{        _id,        url,        "lqip": metadata.lqip,        "aspectRatio": metadata.dimensions.aspectRatio      }    },    gallery[]{      alt,      asset->{        _id,        url,        "lqip": metadata.lqip,        "aspectRatio": metadata.dimensions.aspectRatio      }    },    "articles": *[_type == "article" && references(^._id)]      | order(publishedAt desc)[0...4]{        title,        "slug": slug.current,        category,        mainImage{          alt,          asset->{            _id,            url,            "lqip": metadata.lqip,            "aspectRatio": metadata.dimensions.aspectRatio          }        }      },    seo  }
export type SpotBySlugQueryResult = {
  _id: string;
  name: string | null;
  slug: string | null;
  category: "kura" | "local" | "spot" | "terrace" | null;
  genres: Array<string> | null;
  status: "closed" | "open" | "paused" | null;
  summary: string | null;
  address: string | null;
  hours: string | null;
  holidays: string | null;
  website: string | null;
  instagram: string | null;
  lastVerifiedAt: string | null;
  location: Geopoint | null;
  body: RichText | null;
  mainImage: {
    alt: string | null;
    asset: {
      _id: string;
      url: string | null;
      lqip: string | null;
      aspectRatio: number | null;
    } | null;
  } | null;
  gallery: Array<{
    alt: string | null;
    asset: {
      _id: string;
      url: string | null;
      lqip: string | null;
      aspectRatio: number | null;
    } | null;
  }> | null;
  articles: Array<{
    title: string | null;
    slug: string | null;
    category: "course" | "guide" | "history" | "interview" | "report" | null;
    mainImage: {
      alt: string | null;
      asset: {
        _id: string;
        url: string | null;
        lqip: string | null;
        aspectRatio: number | null;
      } | null;
    } | null;
  }>;
  seo: Seo | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: nearbySpotsQuery
// Query: *[_type == "spot"    && _id != $id    && status != "closed"    && defined(location)    && defined(slug.current)]    | order(geo::distance(location, $location) asc)[0...3]{      name,      "slug": slug.current,      category,      summary,      mainImage{        alt,        asset->{          _id,          url,          "lqip": metadata.lqip,          "aspectRatio": metadata.dimensions.aspectRatio        }      }    }
export type NearbySpotsQueryResult = Array<{
  name: string | null;
  slug: string | null;
  category: "kura" | "local" | "spot" | "terrace" | null;
  summary: string | null;
  mainImage: {
    alt: string | null;
    asset: {
      _id: string;
      url: string | null;
      lqip: string | null;
      aspectRatio: number | null;
    } | null;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: spotListQuery
// Query: *[_type == "spot" && status != "closed" && defined(slug.current)]    | order(name asc){      name,      "slug": slug.current,      category,      genres,      status,      summary,      mainImage{        alt,        asset->{          _id,          url,          "lqip": metadata.lqip,          "aspectRatio": metadata.dimensions.aspectRatio        }      }    }
export type SpotListQueryResult = Array<{
  name: string | null;
  slug: string | null;
  category: "kura" | "local" | "spot" | "terrace" | null;
  genres: Array<string> | null;
  status: "closed" | "open" | "paused" | null;
  summary: string | null;
  mainImage: {
    alt: string | null;
    asset: {
      _id: string;
      url: string | null;
      lqip: string | null;
      aspectRatio: number | null;
    } | null;
  } | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "spot" && defined(slug.current)]{ "slug": slug.current }\n': SpotSlugsQueryResult;
    '\n  *[_type == "spot" && slug.current == $slug][0]{\n    _id,\n    name,\n    "slug": slug.current,\n    category,\n    genres,\n    status,\n    summary,\n    address,\n    hours,\n    holidays,\n    website,\n    instagram,\n    lastVerifiedAt,\n    location,\n    body,\n    mainImage{\n      alt,\n      asset->{\n        _id,\n        url,\n        "lqip": metadata.lqip,\n        "aspectRatio": metadata.dimensions.aspectRatio\n      }\n    },\n    gallery[]{\n      alt,\n      asset->{\n        _id,\n        url,\n        "lqip": metadata.lqip,\n        "aspectRatio": metadata.dimensions.aspectRatio\n      }\n    },\n    "articles": *[_type == "article" && references(^._id)]\n      | order(publishedAt desc)[0...4]{\n        title,\n        "slug": slug.current,\n        category,\n        mainImage{\n          alt,\n          asset->{\n            _id,\n            url,\n            "lqip": metadata.lqip,\n            "aspectRatio": metadata.dimensions.aspectRatio\n          }\n        }\n      },\n    seo\n  }\n': SpotBySlugQueryResult;
    '\n  *[_type == "spot"\n    && _id != $id\n    && status != "closed"\n    && defined(location)\n    && defined(slug.current)]\n    | order(geo::distance(location, $location) asc)[0...3]{\n      name,\n      "slug": slug.current,\n      category,\n      summary,\n      mainImage{\n        alt,\n        asset->{\n          _id,\n          url,\n          "lqip": metadata.lqip,\n          "aspectRatio": metadata.dimensions.aspectRatio\n        }\n      }\n    }\n': NearbySpotsQueryResult;
    '\n  *[_type == "spot" && status != "closed" && defined(slug.current)]\n    | order(name asc){\n      name,\n      "slug": slug.current,\n      category,\n      genres,\n      status,\n      summary,\n      mainImage{\n        alt,\n        asset->{\n          _id,\n          url,\n          "lqip": metadata.lqip,\n          "aspectRatio": metadata.dimensions.aspectRatio\n        }\n      }\n    }\n': SpotListQueryResult;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
